---
title: "Manuscript_draft"
author: "Madeline Frazer"
bibliography: Reproducibility.bib
csl: chicago-fullnote-bibliography.csl 

output: pdf_document
---

# Ants, Plants, and Rats: Effects of Predator Exclusion on Chihuahua Plant Species Abundance

## Introduction

Plant species abundance is a result of many abiotic and biotic factors, including predation. Two main plant predators of Chihuahua plants include ants and rodents.

We aimed to use existing, publicly available data by [@ernest2009] to understand how each predator population (ants and rodents) influence plant species diversity. This data set collected longitudinal data plant abundance data, ant colony data, rodent data, and precipitation data from 1977-2002 across 24 experimental exclusion plots.

## Materials and Methods

The data for this project is publicly available.

For treatment data, a qualitative table of the treatments each plot received on which years can be found in the metadata for this [data set](https://www.esapubs.org/archive/ecol/E090/118/metadata.htm). This project includes a copy of that qualitative table in CSV form (plot_treatments). It also includes a quantitative version, where each unique combination of plot and year has corresponding binary values representing the inclusion or exclusion of kangaroo rats (large rodents), all rodents, *Pogonomyrmex rugosus* (a granivorous ant species), or all ants. 0 = excluded (not present), 1 = included (present). This table is what is used in the following analyses.

While the longitudinal study went from 1977-2002, we only used data from 1989–2002 because that is when plant species-level abundances were consistently recorded.

Using the plant species data, although it was recorded for annuals and perennials both in winter and in summer, and were measured across quadrats within each plot, all species abundances were summed for each plot for each year. Similarly, precipitation data was summed for a total precipitation per year, the same for all plots of that year.

I ran a model comparison to determine what model best represented the data. Negative binomial had an improved AICc score compared to Poisson, so that model structure was used for future models. When comparing all possible combinations of predictive factors (presence/absence of large rodents, presence/absence of all rodents, presence/absence of PORU ants, presence/absence of all ants, and precipitation), the top models contained either presence/absence of all ants or presence/absence of PORU ants and precipitation. Due to the more informative nature of presence/absence of all ants compared to just PORU ants, precipitation and the presence/absence of all ants were chosen as factors in the Negative Binomial model.

For fixed effects, Year and Plot were added (crossed). It was determined that keeping Year in the model made a significant difference compared to just Precipitation, although there was some colinearity.

DHARMa residuals were imperfect, so variance was added to the model (\~ Annual_precip_s + All_ants \* All_rodents). Although the presence of rodents did not predict plant abundnace, it did help explain some of the variation in the data.

Data were checked for temporal autocorrelation, which was not found. Spatial autocorrelation was predicted to explain the remaining variance in the data, but was not able to be accounted for due to lack of geographic coordinates and a precise map of the plot spacing.

It was determined that the outliers did not affect the model.

## Results

Here is a table of which plots had which treatment(s).

Changes in treatment assignments to the 24 experimental plots through time. To help highlight which plots were modified, only changes in treatment after 1985 are recorded below. Blank cells denote no changes in treatment from the previous time period. *Pogonomyrmex rugosus* was a dominant granivorous ant species that declined at the site. Banner-tailed kangaroo rats (*Dipodomys spectabilis*) were a dominant rodent granivore that also declined during the 1980s. (Table modified from Brown 1998). \* plot 24 was not initiated until 1979 (Samson et al. 1992)

```{R  fig.height = 8, fig.width = 8, echo = FALSE}
library(knitr)
plots_treatments <- read.csv("./../data/data_raw/Plot_treatments/plot_treatments.csv")
kable(plots_treatments, align = "cccc", caption = "Plot Treatments")
```

Here is a figure of how the model predicts total plant species abundance using the presence/absence of all ants as a predictor.

```{R,  fig.height = 8, fig.width = 8, echo = FALSE, fig.cap = "Total species abundance data with predicted change in abundance due to ant exclusion"}

source("../scripts/figures/Predicted_Ants.R", local = knitr::knit_global())

```

Here is a figure of how the model predicts total plant species abundance using the total annual precipitation as a predictor.

```{R  fig.height = 8, fig.width = 8, echo = FALSE, include = FALSE, fig.cap = "Total species abundance data with predicted change in abundance due to total annual precipitation"}

source("../scripts/figures/Predicted_AnnualPrecip.R", local = knitr::knit_global())

```

This model still has strong variance in the residuals, as can be seen by the DHARMa package.

```{R  fig.height = 8, fig.width = 8, echo = FALSE, fig.cap = "DHARMa residuals"}

source("../scripts/figures/DHARMa_resids.R", local = knitr::knit_global())

```

In conditional model, the intercept and the presence or absence of all ants were significant predictors of total plant species abundance. The presence of ants negatively impacted total plant species abundance by -0.3170 (p = 0.00569). However, while the presence/absence of Rodents helped account for variance in th model (particularly its interaction with ants, p-value = 0.0904), it was not a significant predictor of plant species abundance (p-value = 0.29836) Annual precipitation (scaled) was not a significant predictor of plant species abundance (p-value = 0.19516).

In dispersion model, annual precipitation (scaled) significantly affected the dispersion of the model (p = 1.30e-07).

## Discussion

The presence or absence of ants on a plot was the strongest predictor of total plant species abundance, controlling for year and plot. The presence of ants negatively affected plant species abundance, much more significantly than the presence of rodents on the plot, although there is likely an interactive effect. Annual precipitation explained the variance of total plant species abundance from the predicted model, but was not itself a significant predictor of total plant species abundance.

## Conclusion

Ants are a significant predator of plants and should be considered in conservation and management plans.

## Bibliography
