---
title: "Preregistration"
author: "Madeline Frazer"
output:
  pdf_document: default
---
This page was last updated on `r format(Sys.time(), '%B %d, %Y')`.

* * *
# Preregistration

## Study Information
### 1. Title

Plant species diversity as a function of predator exclusion in Chihuahua desert

### 2. Authors 
Madeline Frazer (UBC, Canada)

### 3. Description 
This study uses a long-term ecological data reported by Ernest et al. (2009). This dataset records plant species diversity from 24 plots in the Chihuahua desert from 1977 to 2002, where some plots exclude some or all rodents, some plots exclude ants, and some plots exclude both. I aim to determine how predator exclusion (ants, rodents, or both) affected plant species diversity on these plots.

### 4. Hypotheses 
I hypothesize that the plots with no predators have the highest species diversity, and that the plots where rodents only are excluded will have the next highest species diversity. 

## Design Plan

### 5. Study type 
Statistical analysis using long-term publicly available experimental data. 

### 6. Blinding 
Statistical analyses were performed without knowing which plots had which exclusion treatments. 

### 7. Is there any additional blinding in this study?
No.

### 8. Study design 
Randomized block mixed design. 
More info: This question has a variety of possible answers. The key is for a 
researcher to be as detailed as is necessary given the specifics of their design. 
Be careful to determine if every parameter has been specified in the description 
of the study design. There may be some overlap between this question and the 
following questions. That is OK, as long as sufficient detail is given in one of the 
areas to provide all of the requested information. For example, if the study design
describes a complete factorial, 2 X 3 design and the treatments and levels are 
specified previously, you do not have to repeat that information.

### 9. Randomization 
Plots are randomly assigned to an exclusion treatment. 

## Sampling Plan

### 10. Existing data 
Registration prior to analysis of the data: As of the date of submission, the
data exist and you have accessed it, though no analysis has been 
conducted related to the research plan (including calculation of summary 
statistics). A common situation for this scenario when a large dataset 
exists that is used for many different studies over time, or when a data set
is randomly split into a sample for exploratory analyses, and the other 
section of data is reserved for later confirmatory data analysis.
Registration prior to statistical analyses which are performed without extensive knowledge of the data or of associated publications with this data. 

### 11. Explanation of existing data (optional)
This study uses existing data by S. K. Morgan Ernest, Thomas J. Valone, and James H. Brown. 2009. Long-term monitoring and experimental manipulation of a Chihuahuan Desert ecosystem near Portal, Arizona, USA. Ecology 90:1708. 
This study uses a subset of the data that includes matching years for the ant, some rodent, and all rodent exclusions, and precipitation data from the same years. 

### 12. Data collection procedures
Please describe the process by which you will collect your data. If you are using 
human subjects, this should include the population from which you obtain 
subjects, recruitment efforts, payment for participation, how subjects will be 
selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and
your study timeline. For studies that donÍt include human subjects, include 
information about how you will collect samples, duration of data gathering efforts,
source or location of samples, or batch numbers you will use. 
12.2.
Example
: Participants will be recruited through advertisements at local pastry 
shops. Participants will be paid $10 for agreeing to participate (raised to $30 if 
our sample size is not reached within 15 days of beginning recruitment). 
Participants must be at least 18 years old and be able to eat the ingredients of 
the pastries.
12.3.
More information
: The answer to this question requires a specific set of 
instructions so that another person could repeat the data collection procedures 
and recreate the study population. Alternatively, if the study population would be 
unable to be reproduced because it relies on a specific set of circumstances 
unlikely to be recreated (e.g., a community of people from a specific time and 
location), the criteria and methods for creating the group and the rationale for this
unique set of subjects should be clear.
13.
Sample size (required)
13.1.
Describe the sample size of your study. How many units will be analyzed in the 
study? This could be the number of people, birds, classrooms, plots, interactions,
or countries included. If the units are not individuals, then describe the size 
requirements for each unit. If you are using a clustered or multilevel design, how 
many units are you collecting at each level of the analysis?
13.2.
Example
: Our target sample size is 280 participants. We will attempt to recruit up
to 320, assuming that not all will complete the total task. 
13.3.
More information
: For some studies, this will simply be the number of samples 
or the number of clusters. For others, this could be an expected range, minimum,
or maximum number.
14.
Sample size rationale (optional)
14.1.
This could include a power analysis or an arbitrary constraint such as time, 
money, or personnel.
14.2.
Example
: We used the software program G*Power to conduct a power analysis. 
Our goal was to obtain .95 power to detect a medium effect size of .25 at the 
standard .05 alpha error probability. 
14.3.
More information
: This gives you an opportunity to specifically state how the 
sample size will be determined. A wide range of possible answers is acceptable; 
remember that transparency is more important than principled justifications. If 
you state any reason for a sample size upfront, it is better than stating no reason 
and leaving the reader to “fill in the blanks.” Acceptable rationales include: a 
power analysis, an arbitrary number of subjects, or a number based on time or 
monetary constraints.
15.
Stopping rule (optional)
15.1.
If your data collection procedures do not give you full control over your exact 
sample size, specify how you will decide when to terminate your data collection. 
15.2.
Example
: We will post participant sign-up slots by week on the preceding Friday 
night, with 20 spots posted per week. We will post 20 new slots each week if, on 
that Friday night, we are below 320 participants. 
15.3.
More information
: You may specify a stopping rule based on p-values only in 
the specific case of sequential analyses with pre-specified checkpoints, alphas 
levels, and stopping rules. Unacceptable rationales include stopping based on p-
values if checkpoints and stopping rules are not specified. If you have control 
over your sample size, then including a stopping rule is not necessary, though it 
must be clear in this question or a previous question how an exact sample size is
attained.
Variables
In this section you can describe all variables (both manipulated and measured variables) that 
will later be used in your confirmatory analysis plan. In your analysis plan, you will have the 
opportunity to describe how each variable will be used. If you have variables which you are 
measuring for exploratory analyses, you are not required to list them, though you are permitted 
to do so.
16.
Manipulated variables (optional)
16.1.
Describe all variables you plan to manipulate and the levels or treatment arms of 
each variable. This is not applicable to any observational study. 
16.2.
Example:
 We manipulated the percentage of sugar by mass added to brownies. 
The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane 
sugar by mass. 
16.3.
More information
: For any experimental manipulation, you should give a precise
definition of each manipulated variable. This must include a precise description of
the levels at which each variable will be set, or a specific definition for each 
categorical treatment. For example, “loud or quiet,” should instead give either a 
precise decibel level or a means of recreating each level. 'Presence/absence' or 
'positive/negative' is an acceptable description if the variable is precisely 
described.
17.
Measured variables (required)
17.1.
Describe each variable that you will measure. This will include outcome 
measures, as well as any predictors or covariates that you will measure. You do 
not need to include any variables that you plan on collecting if they are not going 
to be included in the confirmatory analyses of this study.
17.2.
Example
: The single outcome variable will be the perceived tastiness of the 
single brownie each participant will eat. We will measure this by asking 
participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 
being ‘not at all’, 7 being ‘a great deal’) and ‘How good did the brownie taste’ (on 
a scale of 1-7, 1 being ‘very bad’, 7 being ‘very good’). 
17.3.
More information
: Observational studies and meta-analyses will include only 
measured variables. As with the previous questions, the answers here must be 
precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too 
vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult 
Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent 
reflectance at 400 nm.'
18.
Indices (optional)
18.1.
If any measurements are  going to be combined into an index (or even a mean), 
what measures will you use and how will they be combined? Include either a 
formula or a precise description of your method. If your are using a more 
complicated statistical method to combine measures (e.g. a factor analysis), you 
can note that here but describe the exact method in the analysis plan section.
18.2.
Example
: We will take the mean of the two questions above to create a single 
measure of ‘brownie enjoyment.’ 
18.3.
More information
: If you are using multiple pieces of data to construct a single 
variable, how will this occur? Both the data that are included and the formula or 
weights for each measure must be specified. Standard summary statistics, such 
as “means” do not require a formula, though more complicated indices require 
either the exact formula or, if it is an established index in the field, the index must
be unambiguously defined. For example, “biodiversity index” is too broad, 
whereas “Shannon’s biodiversity index” is appropriate.
Analysis Plan
You may describe one or more confirmatory analysis in this preregistration. Please remember 
that all analyses specified below must be reported in the final article, and any additional 
analyses must be noted as exploratory or hypothesis generating.
A confirmatory analysis plan must state up front which variables are predictors (independent) 
and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are 
allowed to describe any exploratory work here, but a clear confirmatory analysis is required. 
19.
Statistical models (required)
19.1.
What statistical model will you use to test each hypothesis? Please include the 
type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification 
of the model (this includes each variable that will be included as predictors, 
outcomes, or covariates). Please specify any interactions, subgroup analyses, 
pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan 
on using any positive controls, negative controls, or manipulation checks you 
may mention that here. Remember that any test not included here must be noted
as an exploratory test in your final article. 
19.2.
Example
:  We will use a one-way between subjects ANOVA to analyze our 
results. The manipulated, categorical independent variable is 'sugar' whereas the
dependent variable is our taste index. 
19.3.
More information
: This is perhaps the most important and most complicated 
question within the preregistration. As with all of the other questions, the key is to
provide a specific recipe for analyzing the collected data. Ask yourself: is enough 
detail provided to run the same analysis again with the information provided by 
the user? Be aware for instances where the statistical models appear specific, 
but actually leave openings for the precise test. See the following examples: 
19.3.1.1.
If someone specifies a 2x3 ANOVA with both factors within 
subjects, there is still flexibility with the various types of ANOVAs 
that could be run. Either a repeated measures ANOVA 
(RMANOVA) or a multivariate ANOVA (MANOVA) could be used 
for that design, which are two different tests. 
19.3.1.2.
If you are going to perform a sequential analysis and check after 
50, 100, and 150 samples, you must also specify the p-values 
you’ll test against at those three points.
20.
Transformations (optional)
20.1.
If you plan on transforming, centering, recoding the data, or will require a coding 
scheme for categorical variables, please describe that process.
20.2.
Example
: The “Effect of sugar on brownie tastiness” does not require any 
additional transformations. However, if it were using a regression analysis and 
each level of sweet had been categorically described (e.g. not sweet, somewhat 
sweet, sweet, and very sweet), ‘sweet’ could be dummy coded with ‘not sweet’ 
as the reference category. 
20.3.
More information
: If any categorical predictors are included in a regression, 
indicate how those variables will be coded (e.g. dummy coding, summation 
coding, etc.) and what the reference category will be.
21.
Inference criteria (optional)
21.1.
What criteria will you use to make inferences? Please describe the information 
youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-
off criterion, where appropriate. Will you be using one or two tailed tests for each 
of your analyses? If you are comparing multiple conditions or testing multiple 
hypotheses, will you account for this?
21.2.
Example
: We will use the standard p<.05 criteria for determining if the ANOVA 
and the post hoc test suggest that the results are significantly different from those
expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test 
adjusts for multiple comparisons. 
21.3.
More information: 
P-values, confidence intervals, and effect sizes are standard 
means for making an inference, and any level is acceptable, though some criteria
must be specified in this or previous fields. Bayesian analyses should specify a 
Bayes factor or a credible interval. If you are selecting models, then how will you 
determine the relative quality of each? In regards to multiple comparisons, this is 
a question with few “wrong” answers. In other words, transparency is more 
important than any specific method of controlling the false discovery rate or false 
error rate. One may state an intention to report all tests conducted or one may 
conduct a specific correction procedure; either strategy is acceptable.
22.
Data exclusion (optional)
22.1.
How will you determine what data or samples, if any, to exclude from your 
analyses? How will outliers be handled? Will you use any awareness check?
22.2.
Example
: No checks will be performed to determine eligibility for inclusion 
besides verification that each subject answered each of the three tastiness 
indices. Outliers will be included in the analysis. 
22.3.
More information
: Any rule for excluding a particular set of data is acceptable. 
One may describe rules for excluding a participant or for identifying outlier data.
23.
Missing data (optional)
23.1.
How will you deal with incomplete or missing data?
23.2.
Example
: If a subject does not complete any of the three indices of tastiness, 
that subject will not be included in the analysis.
23.3.
More information
: Any relevant explanation is acceptable. As a final reminder, 
remember that the final analysis must follow the specified plan, and deviations 
must be either strongly justified or included as a separate, exploratory analysis.
24.
Exploratory analysis (optional)
24.1.
If you plan to explore your data set to look for unexpected differences or 
relationships, you may describe those tests here. An exploratory test is any test 
where a prediction is not made up front, or there are multiple possible tests that 
you are going to use. A statistically significant finding in an exploratory test is a 
great way to form a new confirmatory hypothesis, which could be registered at a 
later time. 
24.2.
Example
: We expect that certain demographic traits may be related to taste 
preferences. Therefore, we will look for relationships between demographic 
variables (age, gender, income, and marital status) and the primary outcome 
measures of taste preferences.
Other
25.
Other (Optional)
25.1.
If there is any additional information that you feel needs to be included in your 
preregistration, please enter it here. Literature cited, disclosures of any related 
work such as replications or work that uses the same data, or other context that 
will be helpful for future readers would be appropriate here.


