---
title: "Reproducibility_appendix"
author: "Madeline Frazer"
bibliography: Reproducibility.bib
csl: chicago-fullnote-bibliography.csl 
output: pdf_document
---

This page was last updated on `r format(Sys.time(), '%B %d, %Y')`.

------------------------------------------------------------------------

# Background

This document outlines the steps of all analyses included in my project, "Plant abundance as a function of predator exclusion in the Chihuahua desert," including all data processing, model fitting, and figure generation.

The data is longitudinal ecological data (1977-2002) by [@ernest2009]. It is publicly accessible, accessed [here](https://www.esapubs.org/archive/ecol/E090/118/metadata.htm).

These data are comprised of plant species abundance data, precipitation data, and binary treatment data (predator presence/absence) created from the table found in Table 1 of the online [metadata](https://esapubs.org/archive/ecol/E090/118/metadata.htm) (see Data Import). These data were collected on 24 plots in the Chihuahua desert near Portal, Arizona, USA, with 1 precipitation data point for all plots.

# Data Import

Download CSV files from above site (plant and precipitation data).

For treatments, a qualitative table of the treatments each plot received on which years can be found in the metadata for this [data set](https://www.esapubs.org/archive/ecol/E090/118/metadata.htm). This project includes a copy of that qualitative table in CSV form (plot_treatments). It also includes a quantitative version, where each unique combination of plot and year has corresponding binary values representing the inclusion or exclusion of kangaroo rats (large rodents), all rodents, *Pogonomyrmex rugosus* (a granivorous ant species), or all ants. 0 = excluded (not present), 1 = included (present). This table is what is used in the following analyses.

```{r setup, include=FALSE}
library(formatR)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
```

# Data Cleaning

While the longitudinal study went from 1977-2002, we only used data from 1989–2002 because that is when plant species-level abundances were consistently recorded.

## Plants

In this step, we create a sum of total species detected in each plot per year (combing winter/summer and annual/perennial) and filter to years 1989-2002.

1.  Load packages 'dplyr', and 'tidyr'.

```{R}
library(dplyr)
library(tidyr)
```

2.  Read in the four plant CSV files (1989-2002)

```{R}
#Download the CSV files and insert your path to the files here, or download using the below Github links
plants_1 <- read.csv("https://raw.githubusercontent.com/MkFrazer/chihuahua_plants_ants_rodents/refs/heads/main/data/data_raw/Plants_raw/Portal_plant_summer_annual_19892002.csv")
plants_2 <- read.csv("https://raw.githubusercontent.com/MkFrazer/chihuahua_plants_ants_rodents/refs/heads/main/data/data_raw/Plants_raw/Portal_plant_summer_perennial_19892002.csv")
plants_3 <- read.csv("https://raw.githubusercontent.com/MkFrazer/chihuahua_plants_ants_rodents/refs/heads/main/data/data_raw/Plants_raw/Portal_plant_summer_perennial_19892002.csv")
plants_4 <- read.csv("https://raw.githubusercontent.com/MkFrazer/chihuahua_plants_ants_rodents/refs/heads/main/data/data_raw/Plants_raw/Portal_plant_winter_perennial_19892002.csv")
```

3.  Calculate total abundance per plot per year

```{R}
#Pivot tables to be long ("pivot_longer") while excluding columns "Season", "Life.History", "Year", "Plot", and "Quadrat."
long_plants_1 <- plants_1 %>%
  pivot_longer(
    cols = !c("Season", "Life.History", "Year", "Plot", "Quadrat"),
    names_to = "species",
    values_to = "abundance")    # Change column names to "species" and "abundance."
long_plants_1 <- long_plants_1 %>% mutate(abundance = na_if(abundance, -99))      #Change all "-99" values in "abundance" column to NAs (was not measured). 

long_plants_2 <- plants_2 %>%
  pivot_longer(
    cols = !c("Season", "Life.History", "Year", "Plot", "Quadrat"),
    names_to = "species",
    values_to = "abundance")
long_plants_2 <- long_plants_2 %>% mutate(abundance = na_if(abundance, -99))

long_plants_3 <- plants_3 %>%
  pivot_longer(
    cols = !c("Season", "Life.History", "Year", "Plot", "Quadrat"),
    names_to = "species",
    values_to = "abundance")
long_plants_3 <- long_plants_3 %>% mutate(abundance = na_if(abundance, -99))

long_plants_4 <- plants_4 %>%
  pivot_longer(
    cols = !c("Season", "Life.History", "Year", "Plot", "Quadrat"),
    names_to = "species",
    values_to = "abundance")
long_plants_4 <- long_plants_4 %>% mutate(abundance = na_if(abundance, -99))
```

4.  Create a column for total species abundance per plot per year

```{R}
total_abundance_1 <- long_plants_1 %>% 
  group_by(Plot, Year) %>% #group by Plot and Year
  summarize(
    total_abundance = sum(abundance, na.rm = TRUE), #exclude NAs
    n_species = n(),
    .groups = "drop"    #drop original abundance column
  )

total_abundance_2 <- long_plants_2 %>% 
  group_by(Plot, Year) %>% 
  summarize(
    total_abundance = sum(abundance, na.rm = TRUE),
    n_species = n(),
    .groups = "drop"
  )

total_abundance_3 <- long_plants_3 %>% 
  group_by(Plot, Year) %>% 
  summarize(
    total_abundance = sum(abundance, na.rm = TRUE),
    n_species = n(),
    .groups = "drop"
  )

total_abundance_4 <- long_plants_4 %>% 
  group_by(Plot, Year) %>% 
  summarize(
    total_abundance = sum(abundance, na.rm = TRUE),
    n_species = n(),
    .groups = "drop"
  )
```

5.  Combine 4 data frames into 1 data frame, summing all species abundances

```{R}
plants <- merge(total_abundance_1, total_abundance_2, by = c("Plot","Year"), all = TRUE)   #merge the first two data frames using Plot and Year, keeping all columns
plants <- plants %>%  mutate(total_abundance = total_abundance.x + total_abundance.y, .keep = "unused")   #create a new column that is the sum of the two abundance columns of the previous 2 data frames, and only keeping the new column
plants <- plants %>%  mutate(total_species = n_species.x + n_species.y, .keep = "unused")    #create a new column that is the sum of the two species count columns and keeping only the new column

plants <- merge(plants, total_abundance_3, by = c("Plot", "Year"), all = TRUE)
plants <- plants %>%  mutate(abundance = total_abundance.x + total_abundance.y, .keep = "unused")
plants <- plants %>%  mutate(total_species = n_species + total_species, .keep = "unused")

plants <- merge(plants, total_abundance_4, by = c("Plot", "Year"), all = TRUE)
plants <- plants %>%  mutate(total_abundance = total_abundance + abundance, .keep = "unused")
plants <- plants %>%  mutate(total_species = n_species + total_species, .keep = "unused")
```

6.  Create an "average abundance per species" column.

```{R}
plants <- plants %>% mutate(avg_abundance = total_abundance/total_species)    #sum of total abundance divided by the sum of species counts
```

7.  Filter to years 1989-2002

```{R}
plants_clean <- filter(plants, Year >= 1989)
```

## Precipitation

1.  Load packages (dplyr, here)
```{R}
#load packages
library(dplyr)
```

2.  Read in the two precipitation files (different time periods with different measurement frequencies).
```{R}
#replace with path to your file, or use Github links
precip_1 <- read.csv("https://raw.githubusercontent.com/MkFrazer/chihuahua_plants_ants_rodents/refs/heads/main/data/data_raw/Precip_raw/Portal_precipitation_19801989.csv")
precip_2 <- read.csv("https://raw.githubusercontent.com/MkFrazer/chihuahua_plants_ants_rodents/refs/heads/main/data/data_raw/Precip_raw/Portal_precipitation_19892002.csv")
```

3.  Change column names to be identical between both data frames. Exclude Day and Hour columns from precip2 (unique to precip2).
```{R}
precip_2 <- precip_2 %>% dplyr::select(-Hour, -Day) #don't include Hour or Day
precip_1 <- rename(precip_1, Precipitation = precipitation) #lowercase column name
```

4.  Average precipitation over each year for each precip data frame into a new column.
```{R}
precip_1 <- precip_1 %>% group_by(Year) %>%    #group by Year
            mutate(Annual_precip = sum(Precipitation, na.remove = TRUE)) %>%    #sum precipitation for each year
            ungroup()

precip_2 <- precip_2 %>% group_by(Year) %>% 
  mutate(Annual_precip = sum(Precipitation, na.remove = TRUE)) %>% 
  ungroup()
```

5. Select Year and Annual_precip columns
```{R}
precip_1 <- precip_1 %>% select(Year, Annual_precip)
precip_2 <- precip_2 %>% select(Year, Annual_precip) 
```

6. Combine both data sets into one data frame
```{R}
precip_clean <- full_join(precip_1, precip_2)
precip_clean <- precip_clean %>% distinct()
```

7. Filter to years 1989-2002
```{R}
precip_clean <- filter(precip_clean, Year >= 1989)
```

8. Combine the 1989 columns (because 1989 was split between both data frames)
```{R}
precip_clean <- precip_clean %>% group_by(Year) %>% 
  summarize(Annual_precip = sum(Annual_precip), .groups = "drop")
```

# Analysis

## Combine data frames

1. Read in Treatment CSV file from GitHub, edit column names to match plants and precip data frame column names
```{R}
#read in file
treatments <- read.csv("https://raw.githubusercontent.com/MkFrazer/chihuahua_plants_ants_rodents/refs/heads/main/data/data_processed/treatments.csv") 

#fix treatments column names to match
treatments <- rename(treatments, Plot = PLOT, Year = YEAR, Large_rodents = LARGE_RODENTS, All_rodents = ALL_RODENTS, PORU_ants = PORU_ANTS, All_ants = ALL_ANTS)
```

2. Combine data frames
```{R}
#combine data frames
data <- full_join(precip_clean, plants_clean, by = "Year")
data <- full_join(data, treatments, by = c("Plot", "Year"))

#order columns, filter to >=1989
data <- data[, c("Plot", "Year", "total_species", "total_abundance", "avg_abundance", "Large_rodents", "All_rodents", "PORU_ants", "All_ants", "Annual_precip")]
data<- filter(data, Year >= 1989)   #filter to 1989 and later
data<- data[order(data$Plot), ]  #order rows according to plot number

#make presence/absence treatments binary categories
data$Large_rodents<- as.factor(data$Large_rodents)
data$All_rodents<- as.factor(data$All_rodents)
data$PORU_ants<- as.factor(data$PORU_ants)
data$All_ants<- as.factor(data$All_ants)
```

## Visualization

Create plots comparing dependent variable (total species abundance) according to each independent variable (precipitation, large rodents, all rodents, PORU, or all ants presence/absence). Use z-scores to detect potential outliers to be aware of later on.
```{R}
#plot total species abundance as a factor of precip
plot(data$Annual_precip, data$total_abundance)

#plot total species abundance as a factor of large rodent presence/absence
plot(data$Large_rodents, data$total_abundance)

#plot total species abundance as a factor of all rodent presence/absence
plot(data$All_rodents, data$total_abundance)

#plot total species abundance as a factor of PORU presence/absence
plot(data$PORU_ants, data$total_abundance)

#plot total species abundance as a factor of all ants presence/absence
plot(data$All_ants, data$total_abundance)

#detect potential outliers using z-scores
z_scores <- scale(data$total_abundance)
outliers <- data$total_abundance[abs(z_scores) > 3]
print(outliers)
```

## Model Comparison

1. Load packages 'nlme,' 'MuMIn,' 'MASS.'
```{R}
library(nlme)
library(MuMIn)
library(MASS)
```

1. Total species abundance is count data: compare Poisson and Negative Binomial global models using AIC to determine best model for this data.
```{R}
#load lme4 package
library(lme4)

#scale predictors to help optimizer converge
data$Annual_precip_s <- scale(data$Annual_precip)

#create Poisson global model
global_model_P<- glmer(total_abundance ~ Large_rodents + All_rodents + PORU_ants + All_ants + Annual_precip + (1|Year/Plot), 
         data = data,
         family = poisson(link="log"),   #log link
         na.action = "na.fail")

#create negative binomical global model
global_model_NB <- glmer.nb(total_abundance ~ Large_rodents + All_rodents + PORU_ants + All_ants + Annual_precip_s + (1|Year) +(1|Plot), 
                            data = data,
                            na.action = "na.fail")

#compare AIC values between Poisson and Negative Binomial models
AIC(global_model_P, global_model_NB)

#Negative binomial model was better than the Poisson
```

1. Compare all possible models from global model using dredge() to determine which factors are most important to include in base model (model0). Determine if random factors should be nested or crossed and if confounding between Annual_precip and Year confound model.
```{R}
all_models_NB <- dredge(global_model_NB)
print(all_models_NB)

###either all_ants or PORU_ants need to be included in final model, and Annual precip

#include Year and Plot as random factors

model0 <- glmer.nb(total_abundance ~ All_ants + Annual_precip_s + (1|Year) + (1|Plot), 
                   data = data,
                   na.action = "na.fail")

#Compare Random effects: are Year and Plot nested, or crossed?
model1 <- glmer.nb(total_abundance ~ All_ants + Annual_precip_s + (1|Year/Plot), 
                  data = data,
                  na.action = "na.fail")
AIC(model0,model1)
### better AIC value with crossed random factors, which makes sense. The plots are the same over the years, not different each year.

#however, because there is only a single precipitation value for each year, they are confounded.
#Is it better to include Year as a random factor, or is most of the year-to-year variance captured in Annual_precip?

#exclude Year as a random factor
model2<- glmer.nb(total_abundance ~ All_ants + Annual_precip_s + (1|Plot), 
                     data = data,
                     na.action = "na.fail")
AIC(model0, model2)
### the model with Year as a random factor is significantly better than without Year. Keep year and account for potential confounding in conclusions. But to double-check, let's see how the coefficients differ.

fixef(model2)
fixef(model0)
###the coefficient of Annual Precipitation is about the same between the two models (0.47 without Year as a random factor, 0.41 with Year as a random factor), so we can report this value with relative confidence, even with confounding effects
```

1. Check for residual structure using DHARMa. 
```{R}
#install DHARMa package
library(DHARMa)

#compare simulated residuals to actual residuals
sim <- simulateResiduals(fittedModel = model0)
plot(sim)
###these residuals are all over the place. high deviation.

#check to see if a zero-inflation would be a better model
testZeroInflation(model0)
###No, all values <1

#check to see if adding another variable corrects for residual structure. 
#We saw in Model Selection Table that including All_rodents was only a delta of 1.57 from top model. Let's add All_rodents to see if that improves residuals.
model_rodents <- glmer.nb(total_abundance ~ All_ants + All_rodents + Annual_precip_s + (1|Year) + (1|Plot), 
                          data = data,
                          na.action = "na.fail")

#compare to simulated residuals
sim_rodents <- simulateResiduals(model_rodents)
plot(sim_rodents)
###these residuals seem much cleaner and smoother than before, now it's almost quadratic.

###### After DHARMa, can check using normal residuals

#check residuals vs fitted
plot(fitted(model_rodents), residuals(model_rodents))
###we see an unbalanced x. possibly need a quadratic in model

###### Find cause of residual structure ######

#compare residuals against each thing in the model to see structure

#Annual precip 
plot(data$Annual_precip, residuals(model_rodents))
###Residual variance increases with precipitation, 
###Strong negative skew at higher precipitation values

#All_ants
plot(data$All_ants, residuals(model_rodents))
###wider range when ants are present, both have long negative tails

#All_rodents
plot(data$All_rodents, residuals(model_rodents))
###size and range is similar between groups. both have long negative tails

###need to add variance structure, most likely from Annual_precip but it could help Ants and Rodents, too
```

1. Add variance structure. Use model comparison (AIC) to determine if fixed, power, exponential, or constant + power are the best ways to incorporate residual dispersion into model. In order to do that, we need to use glmmTMB instead of glmer.
```{R}

#install glmmTMB package
library(glmmTMB)

#compare fixed, power, and exponential variance structures

#base model using glmmTMB
model_tmb<- glmmTMB(total_abundance ~ All_ants + All_rodents + Annual_precip_s + (1|Year) + (1|Plot), 
                    data = data,
                    family = nbinom2(link = "log"),
                    na.action = "na.fail",
                    REML = FALSE)

#fixed variance (must use log because Negative binomial uses a log link, and must be offset so that it doesn't produce NA/NANs)
model_fixed <-glmmTMB(total_abundance ~ All_ants + All_rodents + Annual_precip_s + (1|Year) + (1|Plot),
                      data = data,
                      family = nbinom2(link="log"),
                      dispformula = ~offset(log(Annual_precip)),
                      na.action = "na.fail", 
                      REML = FALSE)

#power variance (use log)
model_power <- glmmTMB(total_abundance ~ All_ants + All_rodents + Annual_precip_s + (1|Year) + (1|Plot),
                       data = data,
                       family = nbinom2(link="log"),
                       dispformula = ~log(Annual_precip),
                       na.action = "na.fail", 
                       REML = FALSE)

#exponential variance (already accounted for in glmmTMB model, just need to identify the variable name in dispformula)
model_exp <- glmmTMB(total_abundance ~ All_ants + All_rodents + Annual_precip_s + (1|Year) + (1|Plot),
                     data = data,
                     family = nbinom2(link="log"),
                     dispformula = ~ Annual_precip_s,
                     na.action = "na.fail", 
                     REML = FALSE)

#constant plus power variance (adding a quadratic element)
model_constpower <- glmmTMB(total_abundance ~ All_ants + All_rodents + Annual_precip_s + (1|Year) + (1|Plot),
                         data = data,
                         family = nbinom2(link="log"),
                         dispformula = ~ Annual_precip_s + I(Annual_precip_s^2),
                         na.action = "na.fail", 
                         REML = FALSE)

#compare the above models using AIC
AIC(model_tmb, model_fixed, model_power, model_exp, model_constpower)
### Exponential variance is the better model (or constant power, but they are identical)

#plot residuals of new model including exponential variance structure
plot(fitted(model_exp), residuals(model_exp, type = "pearson"))
#compare to simulated residuals
sim_exp <- simulateResiduals(model_exp)
plot(sim_exp, main = "Exponential Variance")

### There is stil a lot of variance that might be explained by adding missing predictor variables.

#add interactive term between ants and rodents to see if that captures some variation in residuals
model_complex <- glmmTMB(total_abundance ~ All_ants + All_rodents + Annual_precip_s + (1|Year) + (1|Plot),
                       data = data,
                       family = nbinom2(link="log"),
                       dispformula = ~ Annual_precip_s + All_ants * All_rodents,
                       na.action = "na.fail", 
                       REML = FALSE)

#compare to simulated residuals
sim_comp <- simulateResiduals(model_complex)
plot(sim_comp)
###no significant deviation in QQ plot, and smoother lines in DHARMa residual plot
###keep model with complex variance

```


1. Check for temporal autocorrelation
```{R, fig.width=10, fig.height=8}
#plot the residuals according to each year to see if they change over time or according to Year
plot(data$Year, residuals(model_complex, type = "pearson"))
###not too much spread, but we can check using ACF

all_resid <- residuals(model_complex, type = "pearson")
acf(all_resid)   #there might be some sort of temporal autocorrelation

#check for temporal autocorrelation within each plot (is each plot autocorrelated with itself over the years?)

#put residuals into original data frame
data$all_resid <- all_resid   

#new data frame with each plot number
unique_plots <- unique(data$Plot)   

#be able to see 24 plots in Figure window
par(mfrow = c(4, 6)) 
for (p in unique_plots) {
  plot_data <- data[data$Plot == p, ]
  plot_data <- data[order(plot_data$Year),]
  
  acf(plot_data$all_resid, main = paste("Plot ", p)) #include plot number in title
}

###No significant autocorrelation by plot, autocorrelation must be from something else

#restructure Figure window
par(mfrow = c(1,1))
```

1. Check to see if outliers are affecting predicted coefficients. Rerun model without outlier and compare the coefficient with the original model
```{R}
# use Pearson residuals and flag anything beyond ±3
pearson_resids <- residuals(model_complex, type = "pearson")
outlier_idx <- which(abs(pearson_resids) > 3)

# View the suspicious observations
data[outlier_idx, ]

# Plot to see their location
plot(fitted(model_complex), pearson_resids)
###one clear point 6 sd away

#use DHARMa to see the effects of the outlier on the model
sim_complex <- simulateResiduals(model_complex)
testOutliers(sim_complex, type = "bootstrap")

# Visual - outliers flagged in red
plot(sim_complex)

model_no_outlier <- glmmTMB(total_abundance ~ All_ants + All_rodents + Annual_precip_s + (1|Year) + (1|Plot),
                            data = data[-outlier_idx, ],
                            family = nbinom2(link = "log"),
                            dispformula = ~ Annual_precip_s + All_ants * All_rodents,
                            na.action = "na.fail",
                            REML = FALSE)
summary(model_no_outlier)
summary(model_complex)
###coefficients are basically the same, so the outlier isn't affecting the model much
```

# Interpretation

Run summary() on the model to view the coefficients and their values.
```{R}
summary(model_complex)
```

## Results
In conditional model, the intercept and the presence or absence of all ants were significant predictors of total plant species abundance.
The presence of ants negatively impacted total plant species abundance by -0.3170 (p = 0.00569). 
However, while the presence/absence of Rodents helped account for variance in th model (particularly its interaction with ants, p-value = 0.0904), it was not a significant predictor of plant species abundance (p-value = 0.29836)
Annual precipitation (scaled) was not a significant predictor of plant species abundance (p-value = 0.19516). 

In dispersion model, annual precipitation (scaled) significantly affected the dispersion of the model (p = 1.30e-07). 

## Discussion
The presence or absence of ants on a plot was the strongest predictor of total plant species abundance, controlling for year and plot. The presence of ants negatively affected plant species abundance, much more significantly than the presence of rodents on the plot, although there is likely an interactive effect. Annual precipitation explained the variance of total plant species abundance from the predicted model, but was not itself a significant predictor of total plant species abundance. 
```